"""
API Endpoints for the Quick Buy/Sell Service (Day 51)
"""
import logging
from fastapi import APIRouter, Depends, HTTPException, Request
from pydantic import BaseModel
from services.quick_buy_sell_service import QuickBuySellService

router = APIRouter()
logger = logging.getLogger(__name__)

def get_qbs_service(request: Request) -> QuickBuySellService:
    """Dependency to get the QuickBuySellService instance from the app state."""
    if not hasattr(request.app.state, 'quick_buy_sell_service'):
        raise HTTPException(status_code=503, detail="Quick Buy/Sell Service is not available or not enabled.")
    return request.app.state.quick_buy_sell_service

class TokenRequest(BaseModel):
    token_address: str

@router.get("/quick-buy-sell/status", summary="Get Service Status")
async def get_status(service: QuickBuySellService = Depends(get_qbs_service)):
    """
    Retrieves the current status of the Quick Buy/Sell service, including its
    running state, processed tokens, and any errors.
    """
    try:
        return service.get_status()
    except Exception as e:
        logger.error(f"Error getting Quick Buy/Sell service status: {e}")
        raise HTTPException(status_code=500, detail="Failed to retrieve service status.")

@router.get("/quick-buy-sell/logs", summary="Get Recent Trade Logs")
async def get_logs(limit: int = 20, service: QuickBuySellService = Depends(get_qbs_service)):
    """
    Retrieves the most recent trade logs generated by the service.
    """
    try:
        return service.get_trade_logs(limit)
    except Exception as e:
        logger.error(f"Error getting Quick Buy/Sell service logs: {e}")
        raise HTTPException(status_code=500, detail="Failed to retrieve service logs.")

@router.get("/quick-buy-sell/tokens", summary="Get Monitored Tokens")
async def get_monitored_tokens(service: QuickBuySellService = Depends(get_qbs_service)):
    """
    Retrieves the list of token addresses currently being monitored from the
    `qbs_token_addresses.txt` file.
    """
    try:
        tokens = service.get_token_list()
        return {"tokens": tokens, "count": len(tokens)}
    except Exception as e:
        logger.error(f"Error getting monitored tokens: {e}")
        raise HTTPException(status_code=500, detail="Failed to retrieve token list.")

@router.post("/quick-buy-sell/tokens", summary="Add a Token to Monitor")
async def add_token_to_monitor(
    token_request: TokenRequest,
    service: QuickBuySellService = Depends(get_qbs_service)
):
    """
    Adds a new token address to the `qbs_token_addresses.txt` file for monitoring.
    The service will pick it up on its next check.
    """
    try:
        success, message = await service.add_token_to_file(token_request.token_address)
        if not success:
            raise HTTPException(status_code=400, detail=message)
        return {"success": True, "message": message}
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error adding token to file: {e}")
        raise HTTPException(status_code=500, detail=f"Failed to add token: {e}")

@router.get("/quick-buy-sell/config", summary="Get Service Configuration")
async def get_config(service: QuickBuySellService = Depends(get_qbs_service)):
    """
    Retrieves the current configuration being used by the Quick Buy/Sell service.
    """
    return service.get_config()
